# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from mobovidata_dj.bigdata.base_email_model import EmailBase

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=255)),
                ('target_type', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('success', 'Success'), ('partial', 'Partial'), ('error', 'Error')], default='new', max_length=32)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_rows', models.PositiveIntegerField(blank=True, null=True)),
                ('parsed_rows', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CSVImportError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('row', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField()),
                ('data', models.TextField()),
                ('csv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.CSVImport')),
            ],
        ),
    ]
