# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailStats',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('riid', models.CharField(db_index=True, max_length=255)),
                ('window', models.IntegerField(blank=True, choices=[(None, 'Lifetime'), (90, '90'), (60, '60'), (30, '30'), (14, '14'), (7, '7'), (3, '3')], db_index=True, null=True)),
                ('sent', models.IntegerField(default=0)),
                ('opens', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('open_rate', models.FloatField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('cvr', models.FloatField(default=0)),
            ],
            options={
                'ordering': ('-window', '-computed_at'),
            },
        ),
        migrations.AlterModelOptions(
            name='csvimport',
            options={'ordering': ('-parsed_at',)},
        ),
        migrations.AlterField(
            model_name='csvimport',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('started', 'Started'), ('success', 'Success'), ('almost', 'Success (>95%)'), ('partial', 'Partial'), ('error', 'Error')], default='new', max_length=32),
        ),
    ]
