# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20160810_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvimport',
            name='import_to_redshift_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='redshift_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='s3_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='csvimport',
            name='uploaded_to_s3_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
