# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-17 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20160928_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailStats',
        ),
    ]
