# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('supplier_id', models.IntegerField()),
                ('supplier_sku', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier_inventory',
            },
        ),
    ]
