# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierinventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 24, 20, 52, 13, 697353, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 24, 20, 52, 17, 857294, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
