# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-22 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[(None, b'Not yet started'), (b'running', b'Running'), (b'ok', b'OK'), (b'error', b'Error')], max_length=32, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('target', models.CharField(choices=[(b'local', b'Local (server)'), (b'download', b'Download'), (b's3', b'S3')], default=b's3', max_length=32)),
                ('format', models.CharField(choices=[(b'csv', b'CSV'), (b'json', b'JSON')], default=b'csv', max_length=32)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.ReportQuery')),
            ],
        ),
    ]
