# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-25 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportexecution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportquery',
            old_name='target',
            new_name='source',
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='gzip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='metadata_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='on_s3_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportexecution',
            name='s3_filename',
            field=models.BooleanField(default=False),
        ),
    ]
