# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-03 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('mobovidata', '0004_remove_models')
    ]

    operations = [
        migrations.CreateModel(
            name='AdStatWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('ad_id', models.CharField(max_length=128)),
                ('adset_id', models.CharField(max_length=128)),
                ('campaign_id', models.CharField(max_length=128)),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('add_payment_info', models.PositiveIntegerField(default=0)),
                ('add_to_cart', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('reach', models.PositiveIntegerField(default=0)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('spend', models.FloatField(default=0)),
                ('sales_revenue', models.FloatField(default=0)),
                ('total_revenue', models.FloatField(default=0)),
                ('profit', models.FloatField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('cost_per_like', models.FloatField(default=0)),
                ('cost_per_click', models.FloatField(default=0)),
                ('cost_per_sale', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100, null=True)),
                ('campaign_id', models.CharField(max_length=100, null=True)),
                ('ad_set_id', models.CharField(max_length=100, null=True)),
                ('campaign_name', models.CharField(max_length=200, null=True)),
                ('ad_set_name', models.CharField(max_length=200, null=True)),
                ('message', models.CharField(max_length=200, null=True)),
                ('products', models.TextField(null=True)),
                ('bmc_url', models.CharField(max_length=200, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.CharField(max_length=128)),
                ('ad_name', models.CharField(max_length=256)),
                ('ad_set_name', models.CharField(max_length=256)),
                ('category_id', models.IntegerField()),
                ('product_ids', models.TextField()),
                ('campaign_name', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=128)),
                ('status_updated_at', models.DateTimeField()),
            ],
        ),
    ]
