# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0003_product_datamigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='adstatwindow',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='adstatwindow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
