# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-01 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0005_auto_20161031_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookad',
            name='ad_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
