# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-01 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0006_facebookad_ad_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookad',
            name='ad_id',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
