# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-19 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0007_auto_20161031_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookad',
            name='bmc_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
