# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0008_auto_20171019_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookad',
            name='handle_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='productreport',
            name='handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productreport',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
