# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-01 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook', '0009_auto_20171030_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookAPISettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_id', models.CharField(db_index=True, max_length=50)),
                ('account_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('app_secret', models.CharField(max_length=50)),
                ('user_token', models.CharField(max_length=300)),
                ('page_id', models.CharField(max_length=50)),
                ('instagram_actor_id', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
