# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[(b'pending', b'Pending'), (b'active', b'Active'), (b'error', b'Error'), (b'success', b'Success')], default=b'pending', max_length=32)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('instance_number', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=1024, null=True)),
                ('params', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
