# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-22 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('method', models.CharField(blank=True, max_length=1024, null=True)),
                ('limit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name=b'Concurrent limit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(choices=[(b'pending', b'Pending'), (b'active', b'Active'), (b'error', b'Error'), (b'success', b'Success')], default=b'pending', max_length=32)),
                ('task_id', models.CharField(blank=True, db_index=True, max_length=1024, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('instance_number', models.PositiveIntegerField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='taskapp.JobDefinition')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='JobSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'paused', b'Pause'), (b'active', b'Active')], default=b'paused', max_length=16)),
                ('interval', models.PositiveIntegerField()),
                ('unit', models.PositiveIntegerField(choices=[(1, b'seconds'), (60, b'minutes'), (3600, b'hours'), (86400, b'days')], default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='taskapp.JobDefinition')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='CeleryJob',
        ),
    ]
