# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0002_auto_20160822_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'running', b'Running'), (b'success', b'Success'), (b'error', b'Error')], default=b'running', max_length=16)),
                ('output', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
