# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_backuplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexecution',
            name='status',
            field=models.CharField(choices=[(b'pending', b'Pending'), (b'active', b'Active'), (b'error', b'Error'), (b'disappeared', b'Disappeared'), (b'success', b'Success')], default=b'pending', max_length=32),
        ),
    ]
