# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-18 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_auto_20160907_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobschedule',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
