# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-25 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'db_table': 'shopify_product_option_tag',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'db_table': 'shopify_product_tag',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='values',
        ),
        migrations.AlterField(
            model_name='product',
            name='published_scope',
            field=models.CharField(blank=True, choices=[('global', 'global'), ('web', 'web')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producttag',
            name='products',
            field=models.ManyToManyField(to='shopify.Product'),
        ),
        migrations.AddField(
            model_name='productoptionvalue',
            name='options',
            field=models.ManyToManyField(to='shopify.ProductOption'),
        ),
    ]
