# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-27 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_auto_20171024_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('handle', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.CharField(blank=True, choices=[('alpha-asc', 'alpha-asc'), ('alpha-desc', 'alpha-desc'), ('best-selling', 'best-selling'), ('created', 'created'), ('created-desc', 'created-desc'), ('manual', 'manual'), ('price-asc', 'price-asc'), ('price-desc', 'price-desc')], max_length=50, null=True)),
                ('template_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('published_scope', models.CharField(blank=True, choices=[('global', 'global'), ('web', 'web')], max_length=10, null=True)),
                ('disjunctive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'shopify_smart_collection',
            },
        ),
        migrations.CreateModel(
            name='SmartCollectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('src', models.URLField(blank=True, max_length=400, null=True)),
                ('smart_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.SmartCollection')),
            ],
            options={
                'db_table': 'shopify_smart_collection_image',
            },
        ),
        migrations.CreateModel(
            name='SmartCollectionRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, choices=[('greater_than', 'greater_than'), ('less_than', 'less_than'), ('equals', 'equals'), ('not_equals', 'not_equals'), ('starts_with', 'starts_with'), ('ends_with', 'ends_with'), ('contains', 'contains'), ('not_contains', 'not_contains')], max_length=20, null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('column', models.CharField(blank=True, choices=[('title', 'title'), ('type', 'type'), ('vendor', 'vendor'), ('variant_title', 'variant_title'), ('variant_compare_at_price', 'variant_compare_at_price'), ('variant_weight', 'variant_weight'), ('variant_inventory', 'variant_inventory'), ('variant_price', 'variant_price'), ('tag', 'tag')], max_length=20, null=True)),
                ('smart_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.SmartCollection')),
            ],
            options={
                'db_table': 'shopify_smart_collection_rule',
            },
        ),
    ]
