# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-28 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_smartcollection_smartcollectionimage_smartcollectionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartcollectionimage',
            name='smart_collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shopify.SmartCollection'),
        ),
    ]
