# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-31 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_auto_20171028_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='featured_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='variant_ids',
        ),
        migrations.AddField(
            model_name='productimage',
            name='variants',
            field=models.ManyToManyField(blank=True, null=True, to='shopify.ProductVariant'),
        ),
    ]
