# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-31 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_auto_20171030_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='variants',
            field=models.ManyToManyField(blank=True, to='shopify.ProductVariant'),
        ),
    ]
