# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-08 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0006_auto_20171030_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('api_key', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('api_url', models.CharField(max_length=400)),
                ('product_task_run_at', models.DateTimeField(blank=True, null=True)),
                ('collection_task_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shopify_store',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant_id',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='smartcollection',
            name='collection_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartcollection',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store'),
            preserve_default=False,
        ),
    ]
