# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-08 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0007_auto_20171108_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='identifier',
            field=models.SlugField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
