# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-30 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0012_auto_20171130_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='feed_task_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='update_shopify_collection_task_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
