# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-04 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0013_auto_20171130_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='bluetooth',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='model',
            name='bluetooth_version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='collection_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='removable_battery',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='model',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
