# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mobovidata_dj.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0014_auto_20171204_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, storage=mobovidata_dj.core.storages.OverwriteFileSystemStorage(), upload_to='feeds')),
                ('created_at', models.DateTimeField()),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shopify_feed',
            },
        ),
        migrations.RenameField(
            model_name='model',
            old_name='error',
            new_name='error_we',
        ),
        migrations.RenameField(
            model_name='model',
            old_name='synced',
            new_name='synced_we',
        ),
        migrations.RemoveField(
            model_name='store',
            name='feed_task_run_at',
        ),
        migrations.AddField(
            model_name='model',
            name='error_co',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='synced_co',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feed',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store'),
        ),
    ]
