# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-27 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0017_store_order_task_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='feed_excluded',
            field=models.BooleanField(default=False),
        ),
    ]
