# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0018_productvariant_feed_excluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('fraud', 'fraud'), ('inventory', 'inventory'), ('declined', 'declined'), ('other', 'other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shopify.Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address_province_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
