# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-05 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0019_auto_20180103_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='financial_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('authorized', 'authorized'), ('partially_paid', 'partially_paid'), ('paid', 'paid'), ('partially_refunded', 'partially_refunded'), ('refunded', 'refunded'), ('voided', 'voided')], max_length=30, null=True),
        ),
    ]
