# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0021_auto_20180108_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=255)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store')),
            ],
            options={
                'db_table': 'shopify_metadata_product',
            },
        ),
        migrations.CreateModel(
            name='MetadataProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('synced', models.BooleanField(default=False)),
                ('error_msg', models.TextField(blank=True, null=True)),
                ('product_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.MetadataProduct')),
            ],
            options={
                'db_table': 'shopify_metadata_product_attribute',
            },
        ),
        migrations.AlterUniqueTogether(
            name='metadataproductattribute',
            unique_together=set([('product_metadata', 'key')]),
        ),
    ]
