# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mobovidata_dj.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0022_auto_20180115_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUpdateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('file', models.FileField(storage=mobovidata_dj.core.storages.MultipleLevelFileSystemStorage(), upload_to='inventory_update')),
                ('name', models.CharField(max_length=255)),
                ('output', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store')),
            ],
            options={
                'db_table': 'shopify_inventory_update_file',
            },
        ),
        migrations.CreateModel(
            name='InventoryUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('new_qty', models.IntegerField(blank=True, null=True)),
                ('previous_qty', models.IntegerField(blank=True, null=True)),
                ('qoh_qty', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(max_length=255)),
                ('success', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.InventoryUpdateFile')),
            ],
            options={
                'db_table': 'shopify_inventory_update_log',
            },
        ),
    ]
