# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-20 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0023_inventoryupdatefile_inventoryupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('country_id', models.CharField(max_length=3)),
                ('state', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=True)),
                ('total_order', models.IntegerField()),
                ('purchase_order', models.DecimalField(decimal_places=4, max_digits=12)),
                ('return_order', models.DecimalField(decimal_places=4, max_digits=12)),
                ('last_purchase_order', models.DateField(blank=True, null=True)),
                ('create_by', models.CharField(blank=True, max_length=255, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('is_dropship', models.BooleanField(default=False)),
                ('is_regular', models.BooleanField(default=True)),
                ('is_ghost_product', models.BooleanField(default=False)),
                ('enable_promo_pen', models.BooleanField(default=True)),
                ('enable_auto_product', models.BooleanField(default=True)),
                ('invfeed_enable', models.BooleanField(default=False)),
                ('invfeed_url', models.CharField(blank=True, max_length=255, null=True)),
                ('invfeed_user', models.CharField(blank=True, max_length=255, null=True)),
                ('invfeed_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('invfeed_cookie', models.CharField(blank=True, max_length=255, null=True)),
                ('invfeed_prepare', models.CharField(blank=True, max_length=255, null=True)),
                ('invfeed_delimiter', models.CharField(blank=True, max_length=16, null=True)),
                ('invfeed_col_sku', models.CharField(blank=True, max_length=16, null=True)),
                ('invfeed_col_qty', models.CharField(blank=True, max_length=16, null=True)),
                ('shipstation_enable', models.BooleanField(default=False)),
                ('shipstation_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('shipstation_api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('invfeed_header_start', models.IntegerField()),
                ('invfeed_content_start', models.IntegerField()),
                ('invfeed_user_param', models.CharField(blank=True, max_length=255, null=True)),
                ('invfeed_pass_param', models.CharField(blank=True, max_length=255, null=True)),
                ('invfeed_col_disc', models.CharField(blank=True, max_length=255, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store')),
            ],
            options={
                'db_table': 'shopify_inventory_supplier',
            },
        ),
        migrations.CreateModel(
            name='InventorySupplierMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_code', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, max_length=64, null=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.InventorySupplier')),
            ],
            options={
                'db_table': 'shopify_inventory_supplier_mapping',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventorysupplier',
            unique_together=set([('store', 'supplier_id')]),
        ),
    ]
