# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-22 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0024_auto_20180119_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryupdatefile',
            name='vendor_source',
            field=models.CharField(choices=[('stone_edge', 'Stone Edge'), ('ds_hr', 'DS - Highest Rated')], default='stone_edge', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryupdatelog',
            name='synced',
            field=models.BooleanField(default=False),
        ),
    ]
