# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-24 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0025_auto_20180122_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataproductattribute',
            name='m_type',
            field=models.CharField(choices=[('description', 'Description'), ('associated_products', 'Associated products')], default='description', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metadataproductattribute',
            name='status',
            field=models.CharField(choices=[('synced', 'Synced'), ('unsynced', 'Unsynced'), ('error', 'Error')], default='unsynced', max_length=30),
            preserve_default=False,
        ),
    ]
