# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-25 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0027_productextrainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productextrainfo',
            name='associated_products',
            field=models.ManyToManyField(related_name='association', to='shopify.Product'),
        ),
    ]
