# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-25 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0028_productextrainfo_associated_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataproductattribute',
            name='status',
            field=models.CharField(choices=[('error', 'Error'), ('synced', 'Synced'), ('unsynced', 'Unsynced')], default='unsynced', max_length=30),
        ),
    ]
