# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-25 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0029_auto_20180125_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataproductattribute',
            name='synced',
        ),
    ]
