# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-26 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0030_remove_metadataproductattribute_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadataproductattribute',
            name='namespace',
            field=models.CharField(choices=[('product_attributes', 'Product Attributes'), ('variants', 'Variants')], default='product_attributes', max_length=50),
            preserve_default=False,
        ),
    ]
