# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-30 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0033_auto_20180129_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAttributeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_code', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_set_id', models.SmallIntegerField()),
                ('attribute_set_name', models.CharField(blank=True, max_length=255, null=True)),
                ('frontend_label', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'shopify_master_attribute_mapping',
            },
        ),
        migrations.CreateModel(
            name='MasterAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_code', models.CharField(max_length=255)),
                ('frontend_input', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.MasterProduct')),
            ],
            options={
                'db_table': 'shopify_master_attribute_value',
            },
        ),
    ]
