# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-31 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0034_masterattributemapping_masterattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastercategory',
            name='hyphenated_brand_model_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
