# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-31 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0035_mastercategory_hyphenated_brand_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercategory',
            name='brand_model_name',
            field=models.CharField(blank=True, db_index=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='hyphenated_brand_model_name',
            field=models.CharField(blank=True, db_index=True, max_length=510, null=True),
        ),
        migrations.AlterField(
            model_name='mastercategory',
            name='mcid',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='mpid',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='masterproduct',
            name='sku',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
