# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-01 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0036_auto_20180131_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatacollectionattribute',
            name='m_type',
            field=models.CharField(choices=[('master_categories', 'Master Categories'), ('brand_model', 'Brand Model')], max_length=30),
        ),
        migrations.AlterField(
            model_name='metadatacollectionattribute',
            name='namespace',
            field=models.CharField(choices=[('master_categories', 'Master Categories'), ('brandModel', 'Brand Model')], max_length=50),
        ),
    ]
