# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-02 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0038_auto_20180202_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterattributemapping',
            name='attribute_code',
        ),
        migrations.RemoveField(
            model_name='masterattributemapping',
            name='attribute_set_id_old',
        ),
        migrations.RemoveField(
            model_name='masterattributemapping',
            name='attribute_set_name',
        ),
        migrations.RemoveField(
            model_name='masterattributemapping',
            name='frontend_label',
        ),
        migrations.RemoveField(
            model_name='masterattributevalue',
            name='attribute_code',
        ),
        migrations.RemoveField(
            model_name='masterattributevalue',
            name='frontend_input',
        ),
    ]
