# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0039_auto_20180202_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='sku_add_on',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
