# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0040_model_sku_add_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadatacollectionattribute',
            name='m_type',
            field=models.CharField(choices=[('master_categories', 'Master Categories'), ('brand_model', 'Brand Model'), ('defaultAddOnProduct', 'Default Add On Product')], max_length=30),
        ),
        migrations.AlterField(
            model_name='metadatacollectionattribute',
            name='namespace',
            field=models.CharField(choices=[('master_categories', 'Master Categories'), ('brandModel', 'Brand Model'), ('defaultAddOnProduct', 'Default Add On Product')], max_length=50),
        ),
    ]
