# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-02-28 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0041_auto_20180210_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterproduct',
            name='attribute_set_id_old',
        ),
    ]
