# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0042_remove_masterproduct_attribute_set_id_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', jsonfield.fields.JSONField()),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='Error message')),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='UNPROCESSED', max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('PRODUCT_CREATE', 'Product creation')], max_length=40)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store')),
            ],
            options={
                'db_table': 'shopify_transaction',
            },
        ),
    ]
