# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-06 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0043_shopifytransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metafield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('key', models.CharField(db_index=True, max_length=30)),
                ('namespace', models.CharField(db_index=True, max_length=20)),
                ('owner_id', models.CharField(db_index=True, max_length=32)),
                ('owner_resource', models.CharField(db_index=True, max_length=255)),
                ('shopify_id', models.CharField(db_index=True, max_length=32)),
                ('value', models.TextField()),
                ('value_type', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'shopify_metafield',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='metafield_task_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metafield',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store'),
        ),
        migrations.AlterUniqueTogether(
            name='metafield',
            unique_together=set([('owner_id', 'owner_resource', 'store', 'shopify_id')]),
        ),
    ]
