# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0044_auto_20180305_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PRODUCT_CREATE', 'Product creation'), ('PRODUCT_UPDATE', 'Product update')], max_length=40),
        ),
    ]
