# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-28 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0045_auto_20180307_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='shopify_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='adaptor_type',
            field=models.CharField(blank=True, choices=[('apple-30-pin', 'apple-30-pin'), ('apple-8-pin', 'apple-8-pin'), ('lg-chocolate', 'lg-chocolate'), ('micro-usb', 'micro-usb'), ('mini-usb', 'mini-usb'), ('usb-type-c', 'usb-type-c')], max_length=30, null=True),
        ),
    ]
