# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0046_auto_20180328_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('body_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('handle', models.CharField(max_length=255)),
                ('shopify_id', models.CharField(db_index=True, max_length=32)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('shop_id', models.CharField(max_length=32)),
                ('template_suffix', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.Store')),
            ],
            options={
                'db_table': 'shopify_page',
            },
        ),
    ]
