# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-28 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0047_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pages_task_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
