# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-05 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0048_store_pages_task_run_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysuppliermapping',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
