# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-09 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0049_inventorysuppliermapping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='device_type',
            field=models.CharField(blank=True, choices=[('camera', 'camera'), ('cell-phone', 'cell-phone'), ('laptop', 'laptop'), ('mp3-mp4-player', 'mp3-mp4-player'), ('smart-watch', 'smart-watch'), ('tablet', 'tablet')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='headset_type',
            field=models.CharField(blank=True, choices=[('2.5mm', '2.5mm'), ('2.5mm', '2.5mm'), ('3.5mm', '3.5mm'), ('htc-8525', 'htc-8525'), ('lg-chocolate', 'lg-chocolate'), ('micro-usb', 'micro-usb'), ('mini-usb', 'mini-usb'), ('nokia-7210', 'nokia-7210'), ('samsung-e315', 'samsung-e315'), ('samsung-m300', 'samsung-m300'), ('samsung-t809', 'samsung-t809'), ('sony-k750', 'sony-k750')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='pouch_size',
            field=models.CharField(blank=True, choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large'), ('xl', 'xl')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='wireless_charger',
            field=models.NullBooleanField(),
        ),
    ]
