# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0050_auto_20180409_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterattributeset',
            name='attribute_set_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='model',
            name='categories',
            field=models.ManyToManyField(blank=True, to='shopify.MasterAttributeSet'),
        ),
    ]
