# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-10 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0051_auto_20180409_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='headset_type',
            field=models.CharField(blank=True, choices=[('2.5mm', '2.5mm'), ('3.5mm', '3.5mm'), ('htc-8525', 'htc-8525'), ('lg-chocolate', 'lg-chocolate'), ('micro-usb', 'micro-usb'), ('mini-usb', 'mini-usb'), ('nokia-7210', 'nokia-7210'), ('samsung-e315', 'samsung-e315'), ('samsung-m300', 'samsung-m300'), ('samsung-t809', 'samsung-t809'), ('sony-k750', 'sony-k750')], max_length=30, null=True),
        ),
    ]
