# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-12 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0052_auto_20180410_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='collection',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='collection_handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='product_full_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
