version: "2"
services:
  crate:
    command: crate -Des.cluster.name=production
    environment:
      CRATE_HEAP_SIZE: 2g
    image: crate/crate
    restart: on-failure
    volumes:
      - /data/crate:/data
      - ./crate.yml:/crate/config/crate.yml
  crate_staging:
    command: crate -Des.cluster.name=staging
    environment:
      CRATE_HEAP_SIZE: 2g
    image: crate/crate
    restart: on-failure

  nginx_proxy:
    ports:
      - '4200:4200'
      - '4201:4201'
    image: nginx
    links:
    - crate
    - crate_staging
    restart: on-failure
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

