# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('service_name', models.CharField(choices=[('RE', 'Responsys'), ('MA', 'Mandrill')], default='RE', max_length=50)),
                ('endpoint_url', models.URLField()),
                ('endpoint_type', models.CharField(max_length=50)),
                ('endpoint_identifier', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lifecycle_endpoint',
            },
        ),
        migrations.CreateModel(
            name='FilterCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('lifecycle_messaging_stage', models.CharField(default='*', max_length=100)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifecycle.Endpoint')),
            ],
            options={
                'db_table': 'lifecycle_filter',
            },
        ),
    ]
