# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='service_name',
            field=models.CharField(choices=[('campaign_endpoint', 'Responsys - Events'), ('event_endpoint', 'Responsys - Campaigns'), ('Mandrill', 'Mandrill - Campaigns')], max_length=50),
        ),
    ]
