# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0002_auto_20160209_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='endpoint_url',
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='endpoint_type',
            field=models.CharField(choices=[('event', 'Event'), ('campaign', 'Campaign')], max_length=50),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='service_name',
            field=models.CharField(choices=[('responsys', 'Responsys'), ('Mandrill', 'Mandrill - Campaigns')], max_length=50),
        ),
    ]
