# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0003_auto_20160209_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='endpoint_identifier',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='endpoint_name',
            field=models.CharField(default='Cart One', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
