# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0004_auto_20160209_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='endpoint_type',
        ),
    ]
