# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0006_auto_20160209_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainmaker',
            name='service_type',
        ),
        migrations.AddField(
            model_name='rainmaker',
            name='channel',
            field=models.CharField(choices=[('responsys', 'Responsys')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
