# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20160209_1715'),
        ('lifecycle', '0007_auto_20160210_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rainmaker',
            new_name='SalesDirector',
        ),
        migrations.CreateModel(
            name='ProspectDirector',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('analytics.customer',),
        ),
        migrations.AlterModelTable(
            name='salesdirector',
            table='lifecycle_director',
        ),
    ]
