# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 21:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0009_campaign_filter_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbandonedCartCandidateFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Filter')),
                ('inactivity_threshold', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Inactivity threshold (minutes)')),
            ],
            options={
                'abstract': False,
            },
            bases=('lifecycle.filter',),
        ),
        migrations.CreateModel(
            name='ActiveCartInfoFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Filter')),
            ],
            options={
                'abstract': False,
            },
            bases=('lifecycle.filter',),
        ),
        migrations.CreateModel(
            name='DjangoEmailBackendSender',
            fields=[
                ('sender_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Sender')),
                ('from_email', models.EmailField(max_length=254)),
                ('auth_user', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_password', models.CharField(blank=True, max_length=50, null=True)),
                ('connection', models.CharField(blank=True, max_length=200, null=True)),
                ('template', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            bases=('lifecycle.sender',),
        ),
    ]
