# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0010_abandonedcartcandidatefilter_activecartinfofilter_djangoemailbackendsender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'ordering': ['order'], 'verbose_name': 'Filter'},
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='process',
            new_name='campaign',
        ),
    ]
