# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0011_auto_20160302_1808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesDirector',
        ),
        migrations.DeleteModel(
            name='ProspectDirector',
        ),
        migrations.AddField(
            model_name='campaign',
            name='funnel_step',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
