# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 02:08
from __future__ import unicode_literals

from django.db import migrations

def _make_filter_order_unique_for_campaigns(apps, schema_editor):
    """

    @param apps:
    @type apps: django.apps.registry.Apps
    @param schema_editor:
    @type schema_editor:
    @return:
    @rtype:
    """
    Campaign = apps.get_model('lifecycle', 'Campaign') # @type : mobovidata_dj.lifecycle.models.Campaign
    for c in Campaign.objects.all():
        for index, filter in enumerate(c.filters.order_by('order').all()):
            filter.order = index
            filter.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0012_auto_20160304_1114'),
    ]

    operations = [
        migrations.RunPython(
            code=_make_filter_order_unique_for_campaigns,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together=set([('campaign', 'order')]),
        ),
    ]
