# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0013_auto_20160307_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveCartInfoFilter2',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Filter')),
            ],
            options={
                'abstract': False,
            },
            bases=('lifecycle.filter',),
        ),
        migrations.CreateModel(
            name='HasRIIDFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Filter')),
            ],
            options={
                'abstract': False,
            },
            bases=('lifecycle.filter',),
        ),
        migrations.CreateModel(
            name='Responsys',
            fields=[
                ('sender_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Sender')),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('lifecycle.sender',),
        ),
    ]
