# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0015_auto_20160309_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('send_datetime', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifecycle.Campaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifecycle.Sender')),
            ],
        ),
    ]
