# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-24 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0018_auto_20160323_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='lifecycle_messaging_stage',
            field=models.IntegerField(null=True),
        ),
    ]
