# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 04:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0019_campaign_lifecycle_messaging_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InactivityFilter',
            fields=[
                ('filter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Filter')),
                ('inactivity_threshold', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)], verbose_name='Inactivity threshold (minutes)')),
            ],
            options={
                'abstract': False,
            },
            bases=('lifecycle.filter',),
        ),
    ]
