# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0024_mandrill'),
    ]

    operations = [
        migrations.AddField(
            model_name='strandsproductrecsfilter',
            name='recommendation_remplate',
            field=models.CharField(default='prod_6', max_length=50),
        ),
    ]
