# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 15:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0025_strandsproductrecsfilter_recommendation_remplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderconfirmationsendlog',
            name='order_created_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 11, 15, 1, 34, 214185, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderconfirmationsendlog',
            name='order_grand_total',
            field=models.DecimalField(decimal_places=4, default=0.0000, max_digits=12),
            preserve_default=False,
        ),
    ]
