# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0026_auto_20160511_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderconfirmationsendlog',
            old_name='order_grand_total',
            new_name='base_grand_total',
        ),
        migrations.RenameField(
            model_name='orderconfirmationsendlog',
            old_name='order_created_at',
            new_name='order_updated_at',
        ),
    ]
