# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0028_nopdpbrowseabandoninfofilter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riid', models.CharField(max_length=256)),
                ('order_id', models.CharField(max_length=256)),
                ('product_id', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('price_paid', models.DecimalField(decimal_places=4, max_digits=12)),
                ('review_title', models.CharField(max_length=256)),
                ('review_content', models.TextField()),
                ('nickname', models.CharField(max_length=256)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
