# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0029_productreviewentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewentity',
            name='riid',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
