# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0030_auto_20160825_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreviewentity',
            old_name='riid',
            new_name='email',
        ),
    ]
