# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-07 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0029_orderreviewsendlog'),
        ('lifecycle', '0031_auto_20160901_1802'),
    ]

    operations = [
    ]
