# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0032_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderLogMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.IntegerField()),
                ('date', models.CharField(max_length=128)),
                ('hour', models.IntegerField(max_length=6)),
                ('sends_successful', models.IntegerField(max_length=12)),
                ('sends_failed', models.IntegerField()),
            ],
            options={
                'db_table': 'sender_log_monitor',
            },
        ),
    ]
