# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0032_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdaySubmission',
            fields=[
                ('riid', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('frequency', models.TextField()),
                ('color', models.CharField(max_length=128, null=True)),
                ('color_code', models.CharField(max_length=128, null=True)),
                ('con_response_success', models.IntegerField()),
                ('pet_response_success', models.IntegerField()),
                ('con_response', models.TextField()),
                ('pet_response', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
