# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 22:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0033_birthdaysubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaysubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 9, 26, 22, 4, 45, 321722, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
