# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 16:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0034_auto_20160922_1845'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='senderlogmonitor',
            table='lifecycle_senderlogmonitor',
        ),
    ]
