# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0035_auto_20160923_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderlogmonitor',
            name='date',
            field=models.DateField(max_length=128),
        ),
    ]
