# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0036_auto_20160923_1237'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SenderLogMonitor',
        ),
    ]
