# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0038_auto_20161004_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='senderlog',
            old_name='_sends_failed',
            new_name='sends_failed',
        ),
        migrations.RenameField(
            model_name='senderlog',
            old_name='_sends_successful',
            new_name='sends_successful',
        ),
        migrations.RenameField(
            model_name='senderlog',
            old_name='_sends_total',
            new_name='sends_total',
        ),
    ]
