# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0039_auto_20161004_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='senderlog',
            name='sends_failed',
        ),
        migrations.RemoveField(
            model_name='senderlog',
            name='sends_successful',
        ),
        migrations.RemoveField(
            model_name='senderlog',
            name='sends_total',
        ),
    ]
