# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-05 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0041_auto_20161004_1502'),
        ('lifecycle', '0034_birthdaysubmission_created_at'),
    ]

    operations = [
    ]
