# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0042_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfirmationTracking',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=128)),
                ('courier', models.CharField(max_length=128)),
                ('tracking_number', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='senderlog',
            name='failed_sends',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='senderlog',
            name='successful_sends',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='senderlog',
            name='total_sends',
            field=models.IntegerField(default=-1),
        ),
    ]
