# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0043_auto_20161007_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingconfirmationtracking',
            name='confirmation_sent',
            field=models.BooleanField(default=False),
        ),
    ]
