# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-13 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0043_auto_20161012_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderconfirmationemailslog',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='senderlog',
            name='failed_sends',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='senderlog',
            name='successful_sends',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='senderlog',
            name='total_sends',
            field=models.IntegerField(default=-1),
        ),
    ]
