# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-17 20:33
from __future__ import unicode_literals

from django.db import migrations, models

def transfer_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    OrderConfirmationSendLog = apps.get_model('lifecycle', 'OrderConfirmationSendLog')
    OrderConfirmationEmailsLog = apps.get_model('lifecycle', 'OrderConfirmationEmailsLog')
    for r in OrderConfirmationSendLog.objects.all():
        OrderConfirmationEmailsLog.objects.create(
            order_id=r.order_id,
            base_grand_total=r.base_grand_total,
            created_dt=r.created_dt,
            order_updated_at=r.order_updated_at,
            response=1,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0044_auto_20161012_1722'),
    ]

    operations = [
        migrations.RunPython(transfer_data)
    ]
