# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-07 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0044_shippingconfirmationtracking_confirmation_sent'),
    ]

    operations = [
        migrations.RenameModel(
            'shippingconfirmationtracking',
            'shippingstatustracking',
        ),
    ]



