# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-18 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0045_auto_20161017_1333'),
        ('lifecycle', '0045_rename_shippingconf_table'),
    ]

    operations = [
    ]
