# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-23 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0045_rename_shippingconf_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingstatustracking',
            name='nps_sent',
            field=models.BooleanField(default=False),
        ),
    ]
