# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-23 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0046_merge'),
        ('lifecycle', '0046_shippingstatustracking_nps_sent'),
    ]

    operations = [
    ]
