# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0047_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OopsEmailSendLog',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('response', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
