# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-09 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0048_searchabandonfilter'),
        ('lifecycle', '0048_oopsemailsendlog'),
    ]

    operations = [
    ]
