# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-12 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0049_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingstatustracking',
            name='product_review_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SearchAbandon',
        ),
    ]
