# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-16 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifecycle', '0050_auto_20170112_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsysEvent',
            fields=[
                ('sender_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lifecycle.Sender')),
            ],
            options={
                'abstract': False,
            },
            bases=('lifecycle.sender',),
        ),
    ]
