# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-17 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dojomojo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fullname', models.CharField(blank=True, max_length=65, null=True)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('custom_field', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='UNPROCESSED', max_length=15)),
                ('webhook_type', models.CharField(choices=[('DOJOMOJO', 'Dojomojo')], max_length=30)),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='Error message')),
                ('body', jsonfield.fields.JSONField()),
                ('request_meta', jsonfield.fields.JSONField()),
            ],
        ),
    ]
