# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-18 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojomojo',
            name='status',
            field=models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='UNPROCESSED', max_length=15),
        ),
    ]
