# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-02 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_auto_20170418_0832'),
        ('webhooks', '0002_dojomojo_status'),
    ]

    operations = [
    ]
