# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-11 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktransaction',
            name='webhook_type',
            field=models.CharField(choices=[('DOJOMOJO', 'Dojomojo'), ('AFTERSHIP', 'Aftership'), ('UNBOUNCE', 'Unbounce')], max_length=30),
        ),
    ]
