# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-11 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_auto_20170510_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unbounce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('date_submitted', models.DateField()),
                ('ip_address', models.GenericIPAddressField()),
                ('page_name', models.CharField(max_length=100)),
                ('page_url', models.URLField()),
                ('page_uuid', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('UNPROCESSED', 'Unprocessed'), ('PROCESSED', 'Processed'), ('ERROR', 'Error')], default='UNPROCESSED', max_length=15)),
                ('time_submitted', models.TimeField()),
                ('variant', models.CharField(max_length=25)),
            ],
        ),
    ]
