# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-15 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0005_unbounce'),
    ]

    operations = [
        migrations.AddField(
            model_name='unbounce',
            name='date_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
