# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-05 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0006_unbounce_date_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooktransaction',
            name='webhook_type',
            field=models.CharField(choices=[('AFTERSHIP', 'Aftership'), ('DOJOMOJO', 'Dojomojo'), ('SHOPIFY', 'SHOPIFY'), ('UNBOUNCE', 'Unbounce')], max_length=30),
        ),
    ]
