# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('md5', models.CharField(db_index=True, max_length=32)),
                ('first_order_id', models.IntegerField(db_index=True, unique=True)),
                ('first_order_dt', models.DateTimeField()),
                ('num_orders', models.IntegerField()),
            ],
            options={
                'db_table': 'customer_id',
            },
        ),
        migrations.CreateModel(
            name='CustomerIdOrderId',
            fields=[
                ('order_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('repeat_customer', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ltv.CustomerId')),
            ],
            options={
                'db_table': 'customer_id_order_id',
            },
        ),
    ]
