# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ltv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeridorderid',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
