# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ltv', '0002_auto_20160614_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeridorderid',
            name='order_grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
