# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='responsyscredential',
            table='responsys_credential',
        ),
    ]
