# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0002_auto_20160203_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsyscredential',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
