# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0003_auto_20160209_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsyscredential',
            name='campaign_endpoint',
            field=models.CharField(default='/rest/api/v1/campaigns/', max_length=200),
        ),
        migrations.AddField(
            model_name='responsyscredential',
            name='event_endpoint',
            field=models.CharField(default='/rest/api/v1/events/', max_length=200),
        ),
    ]
