# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0004_auto_20160209_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsysIdEmail',
            fields=[
                ('riid', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('md5', models.CharField(db_index=True, max_length=32)),
                ('subscription_status', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'responsys_id_email',
            },
        ),
        migrations.CreateModel(
            name='ResponsysOrderEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('orders', models.IntegerField()),
                ('riid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsys.ResponsysIdEmail')),
            ],
            options={
                'db_table': 'responsys_order_events',
            },
        ),
    ]
