# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0005_responsysidemail_responsysorderevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsysidemail',
            name='subscription_updated_dt',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 28, 15, 35, 36, 491276, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
