# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-28 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0006_responsysidemail_subscription_updated_dt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsysidemail',
            old_name='subscription_updated_dt',
            new_name='modified_dt',
        ),
    ]
