# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0007_auto_20160628_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsysidemail',
            name='modified_dt',
            field=models.DateTimeField(db_index=True),
        ),
    ]
