# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-13 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0008_auto_20160712_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetPromoterScore',
            fields=[
                ('riid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nps_score', models.IntegerField(db_index=True)),
                ('medium', models.CharField(max_length=128)),
                ('campaign', models.CharField(max_length=128)),
                ('promocode', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'responsys_nps',
            },
        ),
    ]
