# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-02 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0009_netpromoterscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsysorderevents',
            name='riid',
        ),
        migrations.AddField(
            model_name='responsysidemail',
            name='responsys_modified_dt',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2016, 11, 2, 22, 18, 11, 144767, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='responsysidemail',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='ResponsysOrderEvents',
        ),
    ]
