# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-02 22:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0010_auto_20161102_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsysidemail',
            name='modified_dt',
        ),
        migrations.AddField(
            model_name='responsysidemail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 11, 2, 22, 22, 37, 357960, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
