# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-02 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0011_auto_20161102_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsysidemail',
            name='responsys_modified_dt',
        ),
    ]
