# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 23:45
from __future__ import unicode_literals

from django.db import migrations
from django.db import connections
import json

def forwards(app, schema):
    cursor = connections['default'].cursor()
    cursor.execute(
            '''
            truncate table responsys_id_email;
            '''
        )

class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0012_remove_responsysidemail_responsys_modified_dt'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
