# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-03 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0012a_truncate_responsysidemail_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptedOutEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riid', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('md5', models.CharField(max_length=32)),
                ('subscription_status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'opted_out_emails',
            },
        ),
        migrations.DeleteModel(
            name='ResponsysIdEmail',
        ),
    ]
