# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-30 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('responsys', '0015_riidemail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='riidemail',
            table='responsys_riid_email',
        ),
    ]
