# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-21 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAvgWeights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_1', models.FloatField()),
                ('day_3', models.FloatField()),
                ('day_7', models.FloatField()),
                ('day_14', models.FloatField()),
                ('day_30', models.FloatField()),
                ('day_90', models.FloatField()),
            ],
        ),
    ]
