# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-11 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductQuarantine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_quarantine_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('quarantine_level', models.CharField(max_length=128)),
                ('quarantine_level_updated_at', models.DateTimeField(blank=True)),
            ],
        ),
    ]
