# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-12 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0002_productquarantine'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgingInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_in_stock', models.IntegerField(blank=True, null=True)),
                ('back_orders', models.IntegerField(blank=True, null=True)),
                ('base_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('margin', models.CharField(blank=True, max_length=128)),
                ('image', models.TextField(blank=True, null=True)),
                ('vendor_sku', models.TextField(blank=True, null=True)),
                ('vendor_name', models.TextField(blank=True, null=True)),
                ('attribute_set', models.CharField(blank=True, max_length=128, null=True)),
                ('category', models.CharField(blank=True, max_length=128, null=True)),
                ('day_1', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('day_3', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('day_7', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('day_14', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('day_30', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('day_90', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_day1_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_day3_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_day7_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_day14_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_day30_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_day90_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('po_run_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('forecast_daily_demand', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('inventory_days_remain', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('pending_po_id', models.TextField(blank=True, null=True)),
                ('pending_po_qty', models.TextField(blank=True, null=True)),
                ('pending_po_date', models.TextField(blank=True, null=True)),
                ('pending_po_len', models.TextField(blank=True, null=True)),
                ('last_received_date', models.DateTimeField(blank=True, null=True)),
                ('last_received_qty', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
    ]
