# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-20 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('salesreport', '0003_aginginventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='aginginventory',
            name='brand_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aginginventory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 20, 0, 26, 30, 972831, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aginginventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 20, 0, 26, 57, 846797, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
