# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('riid', models.IntegerField(null=True, unique=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('cart_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_cart',
            },
        ),
        migrations.CreateModel(
            name='CustomerLifecycleTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funnel_step', models.IntegerField(default=0)),
                ('lifecycle_messaging_stage', models.IntegerField(default=0)),
                ('lifecycle_messaging_data', models.TextField(blank=True, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.Customer')),
            ],
            options={
                'db_table': 'customer_lifecycle_tracking',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('order_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_order',
            },
        ),
        migrations.CreateModel(
            name='CustomerPageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_path', models.CharField(max_length=255)),
                ('product_fullid', models.CharField(blank=True, max_length=100, null=True)),
                ('url_parameters', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_pageview',
            },
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('session_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('device_headers', models.CharField(max_length=200)),
                ('num_page_views', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Customer')),
            ],
            options={
                'db_table': 'customer_session',
            },
        ),
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riid_field', models.IntegerField(db_column='RIID_')),
                ('order_id', models.IntegerField(db_column='ORDER_ID')),
                ('product_id', models.CharField(db_column='PRODUCT_ID', max_length=30)),
                ('rating', models.IntegerField(db_column='RATING')),
                ('price_paid', models.FloatField(db_column='PRICE_PAID')),
                ('qty', models.IntegerField(db_column='QTY')),
                ('review_title', models.TextField(blank=True, db_column='REVIEW_TITLE', null=True)),
                ('review_content', models.TextField(blank=True, db_column='REVIEW_CONTENT', null=True)),
                ('nickname', models.TextField(blank=True, db_column='NICKNAME', null=True)),
                ('review_dt', models.DateTimeField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_reviews',
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='ResponsysCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('endpoint', models.URLField()),
                ('modified_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerpageview',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.CustomerSession'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.CustomerSession'),
        ),
        migrations.AddField(
            model_name='customercart',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.CustomerSession'),
        ),
    ]
