# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponsysCredential',
        ),
    ]
