# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20160209_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customersession',
            options={},
        ),
    ]
