# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20160209_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='riid',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
    ]
