# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_gmailademails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStrandsId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strands_id', models.CharField(max_length=32)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Customer')),
            ],
            options={
                'db_table': 'customer_strands_id',
            },
        ),
    ]
