# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_customerstrandsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstrandsid',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.Customer'),
        ),
    ]
