# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-29 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20160420_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstrandsid',
            name='strands_id',
            field=models.CharField(max_length=50),
        ),
    ]
