# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_facebookademails'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobovidaCustomerEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_md5', models.CharField(max_length=128)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mobovida_customer_email',
            },
        ),
    ]
