# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_mobovidacustomeremails'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignUpTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.IntegerField()),
                ('unsubscribe_email', models.IntegerField()),
                ('net_change', models.IntegerField()),
            ],
            options={
                'db_table': 'track_email_signup',
            },
        ),
    ]
