# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_emailsignuptrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignuptrack',
            name='analysis_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
