# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0013_emailsignuptrack_analysis_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsignuptrack',
            name='day',
            field=models.CharField(blank=True, help_text='date for email sign up and unsubscribe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailsignuptrack',
            name='analysis_date',
            field=models.DateTimeField(blank=True, help_text='analysis date', null=True),
        ),
        migrations.AlterField(
            model_name='emailsignuptrack',
            name='net_change',
            field=models.IntegerField(help_text='total net change, new email sign ups - email unsubs'),
        ),
        migrations.AlterField(
            model_name='emailsignuptrack',
            name='new_email',
            field=models.IntegerField(help_text='The count of new email sign ups'),
        ),
        migrations.AlterField(
            model_name='emailsignuptrack',
            name='unsubscribe_email',
            field=models.IntegerField(help_text='The count of email unsubscribes'),
        ),
    ]
