# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-25 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0014_auto_20160620_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsignuptrack',
            name='id',
        ),
        migrations.RemoveField(
            model_name='emailsignuptrack',
            name='net_change',
        ),
        migrations.AlterField(
            model_name='emailsignuptrack',
            name='day',
            field=models.CharField(blank=True, default=0, help_text='date for email sign up and unsubscribe', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
