# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-09 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0016_auto_20160815_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('riid', models.IntegerField(primary_key=True, serialize=False)),
                ('device', models.CharField(max_length=128)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('modified_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_device',
            },
        ),
    ]
