# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_auto_20170110_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdevice',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
