from decimal import Decimal
import pytz
import datetime

BUILD_ORDER_INFO_TEST = [{u'billing_address': {'address_type': u'billing',
                                               'city': u'Fullerton',
                                               'company': None,
                                               'country_id': u'US',
                                               'customer_address_id': None,
                                               'customer_id': None,
                                               'email': u'kenny@mobovida.com',
                                               'entity_id': 405777L,
                                               'fax': None,
                                               'firstname': u'Ed',
                                               'lastname': u'Choi',
                                               'middlename': None,
                                               'parent': 202889L,
                                               'postcode': u'92831',
                                               'prefix': None,
                                               'quote_address_id': None,
                                               'region': u'California',
                                               'region_id': 12L,
                                               'street': u'1375 S Acacia Ave',
                                               'suffix': None,
                                               'telephone': u'17144783223',
                                               'vat_id': None,
                                               'vat_is_valid': None,
                                               'vat_request_date': None,
                                               'vat_request_id': None,
                                               'vat_request_success': None},
                          u'coupon_code': None,
                          u'created_at': datetime.datetime(2015, 8, 6, 16, 59, 33, tzinfo=pytz.utc),
                          u'customer_email': u'kenny@mobovida.com',
                          u'discount_amount': Decimal('0.0000'),
                          u'grand_total': Decimal('9.2200'),
                          u'items_count': 2,
                          u'order_id': u'200198066',
                          u'products': [{u'added_from_category_id': 23195L,
                                         u'image': u'http://cellularoutfitter.com/media/catalog/product/m/i/micro-usb-car-charger.jpg',
                                         u'name': u'Samsung Galaxy S4 Micro USB Car Charger',
                                         u'og_url_path': u'micro-usb-car-charger.html',
                                         u'price': 19.99,
                                         u'product_id': 246L,
                                         u'qty': 1,
                                         u'save_dollars': 18,
                                         u'save_percent': 85.04,
                                         u'sku': u'CC1-MOT-00V9-01',
                                         u'special_price': Decimal('2.9900'),
                                         u'total': 2.99,
                                         u'url_path': u'http://cellularoutfitter.com/samsung/galaxy-s4/phone-chargers/micro-usb-car-charger.html'},
                                        {u'added_from_category_id': 32L,
                                         u'image': u'http://cellularoutfitter.com/media/catalog/product/2/-/2-in-1-touchscreen-stylus-_-ballpoint-pen-w-clip.jpg',
                                         u'name': u'2-in-1 Touchscreen Stylus & Ballpoint Pen w/Clip',
                                         u'og_url_path': u'2-in-1-touchscreen-stylus-ballpoint-pen-w-clip.html',
                                         u'price': 29.99,
                                         u'product_id': 5631L,
                                         u'qty': 1,
                                         u'save_dollars': 30,
                                         u'save_percent': 0.0,
                                         u'sku': u'STY-PEN-UNIV-02',
                                         u'special_price': Decimal('0.0000'),
                                         u'total': 0.0,
                                         u'url_path': u'http://cellularoutfitter.com/universal-accessories/2-in-1-touchscreen-stylus-ballpoint-pen-w-clip.html'}],
                          u'shipping_address': {'address_type': u'shipping',
                                                'city': u'Fullerton',
                                                'company': None,
                                                'country_id': u'US',
                                                'customer_address_id': None,
                                                'customer_id': None,
                                                'email': u'kenny@mobovida.com',
                                                'entity_id': 405778L,
                                                'fax': None,
                                                'firstname': u'Ed',
                                                'lastname': u'Choi',
                                                'middlename': None,
                                                'parent': 202889L,
                                                'postcode': u'92831',
                                                'prefix': None,
                                                'quote_address_id': None,
                                                'region': u'California',
                                                'region_id': 12L,
                                                'street': u'1375 S Acacia Ave',
                                                'suffix': None,
                                                'telephone': u'17144783223',
                                                'vat_id': None,
                                                'vat_is_valid': None,
                                                'vat_request_date': None,
                                                'vat_request_id': None,
                                                'vat_request_success': None},
                          u'shipping_amount': Decimal('5.9900'),
                          u'shipping_description': u'USPS First Class (4-10 business days)',
                          u'subtotal': Decimal('2.9900'),
                          u'tax_amount': Decimal('0.2400'),
                          u'updated_at': datetime.datetime(2015, 8, 6, 17, 25, 9, tzinfo=pytz.utc)}]


ORDER_REQUEST_PAYLOAD = {'recipientData': [{'optionalData': [{'name': 'product_attributes',
     'value': 'og_url_path;;-;;save_percent;;-;;price;;-;;save_dollars;;-;;special_price;;-;;qty;;-;;url_path;;-;;name;;-;;sku;;-;;total;;-;;product_id;;-;;added_from_category_id;;-;;image'},
    {'name': 'strands_product_attributes',
     'value': 'name;;-;;save_percent;;-;;price;;-;;save_dollars;;-;;special_price;;-;;url_path;;-;;image'},
    {'name': 'riid', 'value': u'312597965'},
    {'name': u'customer_email', 'value': u'kenny@mobovida.com'},
    {'name': u'order_id', 'value': u'200198066'},
    {'name': 'includes_strands', 'value': 'yes'},
    {'name': u'updated_at', 'value': '2015-08-06T17:25:09+00:00'},
    {'name': 'strands_products',
     'value': 'Apple iPhone 5 Screen Protector;-;83.87;-;16.99;-;14;-;2.74;-;http://www.cellularoutfitter.com/apple/iphone-5/phone-screen-protectors/iphone-5s-screen-protector.html;-;http://www.cellularoutfitter.com/media/catalog/product/cache/2/image/265x/9df78eab33525d08d6e5fb8d27136e95/S/C/SCR-APL-IPH5-01_NEW_0.jpg;;-;;Motorola Droid Turbo Screen Protector;-;83.87;-;16.99;-;14;-;2.74;-;http://www.cellularoutfitter.com/motorola/droid-turbo/phone-screen-protectors/motorola-droid-turbo-screen-protector-clear.html;-;http://www.cellularoutfitter.com/media/catalog/product/cache/2/image/265x/9df78eab33525d08d6e5fb8d27136e95/S/C/SCR-MOT-TURB-01_NEW_0.jpg;;-;;Motorola Droid Turbo Micro USB Home and Travel Charger;-;85.04;-;19.99;-;17;-;2.99;-;http://www.cellularoutfitter.com/motorola/droid-turbo/phone-chargers/micro-usb-home-and-travel-charger.html;-;http://www.cellularoutfitter.com/media/catalog/product/cache/2/image/265x/9df78eab33525d08d6e5fb8d27136e95/m/i/micro-usb-home-and-travel-charger.jpg;;-;;Motorola Droid Turbo Tempered Glass Screen Protector;-;70.02;-;29.99;-;21;-;8.99;-;http://www.cellularoutfitter.com/motorola/droid-turbo/phone-screen-protectors/mot-turb-tempered-glass-screen-protector-clear.html;-;http://www.cellularoutfitter.com/media/catalog/product/cache/2/image/265x/9df78eab33525d08d6e5fb8d27136e95/S/C/SCR-MOT-TURB-TG01_NEW_2.jpg;;-;;Motorola Droid Turbo - My.Carbon 3-in-1 Armor Rugged Case, Black/Black;-;60.02;-;29.99;-;18;-;11.99;-;http://www.cellularoutfitter.com/motorola/droid-turbo/phone-cases-covers/motorola-droid-turbo-my-carbon-3-in-1-armor-rugged-case-black-black.html;-;http://www.cellularoutfitter.com/media/catalog/product/cache/2/image/265x/9df78eab33525d08d6e5fb8d27136e95/f/p/fpx-mot-turb-my10-1.jpg;;-;;Motorola Droid Turbo Slim Fit Hard Plastic Case, Black;-;86.83;-;24.99;-;22;-;3.29;-;http://www.cellularoutfitter.com/motorola/droid-turbo/phone-cases-covers/motorola-droid-turbo-rubber-case-black.html;-;http://www.cellularoutfitter.com/media/catalog/product/cache/2/image/265x/9df78eab33525d08d6e5fb8d27136e95/F/P/FP3-MOT-TURB-10_NEW_1.jpg'},
    {'name': u'BILLING_CITY', 'value': u'Fullerton'},
    {'name': u'BILLING_FNAME', 'value': u'Ed'},
    {'name': u'BILLING_LNAME', 'value': u'Choi'},
    {'name': u'BILLING_STATE', 'value': u'California'},
    {'name': u'BILLING_PHONE', 'value': u'17144783223'},
    {'name': u'BILLING_STREET', 'value': u'1375 S Acacia Ave'},
    {'name': u'BILLING_ZIP', 'value': u'92831'},
    {'name': u'subtotal', 'value': '2.99'},
    {'name': u'discount_amount', 'value': '0.0'},
    {'name': u'grand_total', 'value': '9.22'},
    {'name': u'items_count', 'value': 2},
    {'name': u'tax_amount', 'value': '0.24'},
    {'name': u'created_at', 'value': '2015-08-06T16:59:33+00:00'},
    {'name': u'shipping_amount', 'value': '5.99'},
    {'name': u'coupon_code', 'value': None},
    {'name': 'products',
     'value': 'micro-usb-car-charger.html;-;85.04;-;19.99;-;18;-;2.99;-;1;-;http://cellularoutfitter.com/samsung/galaxy-s4/phone-chargers/micro-usb-car-charger.html;-;Samsung Galaxy S4 Micro USB Car Charger;-;CC1-MOT-00V9-01;-;2.99;-;246;-;23195;-;http://cellularoutfitter.com/media/catalog/product/m/i/micro-usb-car-charger.jpg;;-;;2-in-1-touchscreen-stylus-ballpoint-pen-w-clip.html;-;0.0;-;29.99;-;30;-;0.0;-;1;-;http://cellularoutfitter.com/universal-accessories/2-in-1-touchscreen-stylus-ballpoint-pen-w-clip.html;-;2-in-1 Touchscreen Stylus & Ballpoint Pen w/Clip;-;STY-PEN-UNIV-02;-;0.0;-;5631;-;32;-;http://cellularoutfitter.com/media/catalog/product/2/-/2-in-1-touchscreen-stylus-_-ballpoint-pen-w-clip.jpg'},
    {'name': u'SHIPPING_CITY', 'value': u'Fullerton'},
    {'name': u'SHIPPING_FNAME', 'value': u'Ed'},
    {'name': u'SHIPPING_LNAME', 'value': u'Choi'},
    {'name': u'SHIPPING_STATE', 'value': u'California'},
    {'name': u'SHIPPING_PHONE', 'value': u'17144783223'},
    {'name': u'SHIPPING_STREET', 'value': u'1375 S Acacia Ave'},
    {'name': u'SHIPPING_ZIP', 'value': u'92831'},
    {'name': u'shipping_description',
     'value': u'USPS First Class (4-10 business days)'}],
   'recipient': {'emailFormat': 'HTML_FORMAT',
    'listName': {'folderName': '!MageData', 'objectName': 'CONTACT_LIST'},
    'recipientId': u'312597965'}}]}
