# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-08 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecatproductdata',
            name='product_id',
            field=models.CharField(max_length=15),
        ),
    ]
