# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0002_auto_20160908_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecatproductdata',
            old_name='orders',
            new_name='visits',
        ),
        migrations.AddField(
            model_name='sitecatproductdata',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sitecatproductdata',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
