# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0003_auto_20160911_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecatproductdata',
            name='visits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
