# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0005_auto_20160911_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecatproductdata',
            name='date',
        ),
        migrations.AddField(
            model_name='sitecatproductdata',
            name='day',
            field=models.DateField(max_length=128, null=True),
        ),
    ]
