# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0006_auto_20160911_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitecatproductdata',
            old_name='day',
            new_name='date',
        ),
    ]
