# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-13 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0007_auto_20160911_2252'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sitecatproductdata',
            unique_together=set([('product_id', 'date')]),
        ),
    ]
