# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 16:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0008_auto_20160913_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecatproductdata',
            name='id',
        ),
        migrations.AddField(
            model_name='sitecatproductdata',
            name='product_id_date',
            field=models.IntegerField(default=0000000000000, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitecatproductdata',
            name='date',
            field=models.DateField(db_index=True, default=datetime.datetime(2016, 9, 20, 16, 56, 39, 698910, tzinfo=utc), max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitecatproductdata',
            name='product_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
