# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0009_auto_20160920_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecatproductdata',
            name='product_id_date',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
