# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0010_auto_20160920_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecatproductdata',
            name='sku',
            field=models.CharField(db_index=True, default='xxx-xxx-xxx', max_length=64),
            preserve_default=False,
        ),
    ]
