# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniture', '0011_sitecatproductdata_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecatproductdata',
            name='cart_additions',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sitecatproductdata',
            name='cart_removals',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sitecatproductdata',
            name='orders',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sitecatproductdata',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
    ]
